vfxForFree: true
BannersForFree: true
tauntsForFree: true
abilityModsForFree: true
skinsForFree: true
emojisForFree: true
titlesForFree: true
loadingScreenBackgroundForFree: true
overconsForFree: true
allCharactersForFree: true
charactersLevels: 20