MOTDPopUpText: ""
MOTDText: "Join the project Discord: https://discord.gg/yrZRHJaAUg"
PatchNotesCommitsUrl: https://api.github.com/repos/Zheneq/EvoS/commits?per_page=10
Discord:
  Enabled: false
  UseDiscordBot: true # Enable if you want the bot in your discord channel to enchancement to the webhooks adds commands and  chat from discord to ar
  BotToken: "" # Enter the bots token leave empty to disable
  BotChannelId: 0 # Enter the channel id for 2way chat (usualy the LobbyChannel id)
  AdminChannel: # Discord Webhook for admin reports
    Webhook: ""
    ThreadId: # leave empty to post into the channel
  AdminEnableUserReports: true
  AdminUserReportThreadId:
  AdminEnableChatAudit: true
  AdminChatAuditThreadId:
  AdminEnableLog: false
  AdminLogThreadId: 
  GameLogChannel:
    Webhook: "" # Discord Webhook for game results
    ThreadId: 
  LobbyChannel:
    Webhook: "" # Discord Webhook for lobby status and chat
    ThreadId:
  LobbyEnableChat: true
  LobbyEnableServerStatus: true
  LobbyChannelUpdatePeriodSeconds: 300
  LobbyChannelUpdateOnChangeOnly: true