MOTDPopUpText: ""
MOTDText: "Join the project Discord: https://discord.gg/yrZRHJaAUg"
PatchNotesCommitsUrl: https://api.github.com/repos/Zheneq/EvoS/commits?per_page=10
Discord:
  Enabled: true
  BotToken: "" # Enter the bots token
  AdminChannel: 0 # Discord channel id for admin reports
  AdminEnableUserReports: true
  AdminUserReportChannelId: 0 # Discord channel id from ingame user/bug reports
  AdminEnableChatAudit: true
  AdminChatAuditChannelId: 0
  GameLogChannel: 0 # Discord channel Id for game results
  LobbyChannel: 0 # Discord channel Id for lobby status and chat
  LobbyEnableChat: true
  LobbyEnableServerStatus: true
  LobbyChannelUpdatePeriodSeconds: 300
  LobbyChannelUpdateOnChangeOnly: true