DirectoryServerPort: 6050
LobbyServerAddress: 127.0.0.1
LobbyServerPort: 6060
GameServerExecutable: ""
SteamWebApiKey: ""
Database:
  Type: "None" # Set to "Mongo" and fill out variables below to use database
  URI: "localhost:27017"
  User: "user"
  Password: "password"
  Database: "atlas"
  Salt: "salt"
  MongoDbSrv: false
  UseCredentials: true # Set to false to ignore user and password in database