FreeVfx: true
FreeBanners: true
FreeTaunts: true
FreeAbilitMods: true
FreeSkins: true
FreeEmojis: true
FreeTitles: true
FreeLoadingScreenBackground: true
FreeOvercons: true
FreeAllCharacters: true
StartingCharactersLevel: 100